## 【問題1】行列積を手計算する
\begin{eqnarray}
\begin{array}{c}
C\\
\end{array}
=
\left[
\begin{array}{ccc}
-1*0+2*0+3*2 & -1*2+2*2+3*9 & -1*1+2*(-8)+3*(-1) \\ 
4*0-5*0+6*2 & 4*2-5*2+6*9 & 4*1-5*(-8)+6*(-1) \\ 
7*0+8*0-9*2 & 7*2+8*2-9*9 & 7*1+8*(-8)-9*(-1)
\end{array}
\right]
\end{eqnarray}

\begin{eqnarray}
\begin{array}{c}
C\\
\end{array}
=
\left[
\begin{array}{ccc}
6 & 29 & -20 \\ 
12 & 52 & 38 \\ 
-18 & -51 & -48
\end{array}
\right]
\end{eqnarray}

In [22]:
#【問題2】NumPyの関数による計算
import numpy as np
a_ndarray = np.array([[-1, 2, 3], 
                                        [4, -5, 6],
                                        [7, 8, -9]])

b_ndarray = np.array([[0, 2, 1], 
                                        [0, 2, -8], 
                                        [2, 9, -1]])


c_ndarray = a_ndarray @ b_ndarray
print(c_ndarray)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [23]:
#【問題4】行列積を行う関数の作成
#　※問題3について検討をしていたところ、問題4も満足するコードが完成したため、問題3用のプログラムは作成していません。

import numpy as np

def compute_matrix_product(a_ndarray, b_ndarray):
    
    #行列Aのサイズ(m×n)を取得
    a_size_m = a_ndarray.shape[0]
    a_size_n = a_ndarray.shape[1]
    
    #行列Bのサイズ(m×n)を取得
    b_size_m = b_ndarray.shape[0]
    b_size_n = b_ndarray.shape[1]
    
    #行列Cのサイズの決定。各要素の初期値は０とする。
    c_ndarray = np.zeros(a_size_m * b_size_n).reshape(a_size_m, b_size_n)
    
    #行列積計算
    for i in range(a_size_m):
        for j in range(b_size_n):
            for k in range(a_size_n):
                c_ndarray[i, j] += a_ndarray[i, k] * b_ndarray[k, j]
    
    return c_ndarray

a_ndarray = np.array([[-1, 2, 3], 
                                        [4, -5, 6],
                                        [7, 8, -9]])

b_ndarray = np.array([[0, 2, 1], 
                                        [0, 2, -8], 
                                        [2, 9, -1]])

c_ndarray = compute_matrix_product(a_ndarray, b_ndarray)
print(c_ndarray) 

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


In [29]:
#【問題5】計算が定義されない入力を判定する
import numpy as np

def compute_matrix_product(a_ndarray, b_ndarray):
    
    #行列Aのサイズ(m×n)を取得
    a_size_m = a_ndarray.shape[0]
    a_size_n = a_ndarray.shape[1]
    
    #行列Bのサイズ(m×n)を取得
    b_size_m = b_ndarray.shape[0]
    b_size_n = b_ndarray.shape[1]
    
    #行列積の計算可否を確認
    if a_size_n != b_size_m:
        print("行列のサイズに問題があるため、計算結果が誤っている可能性があります。")
    
    #行列Cのサイズの決定。各要素の初期値は０とする。
    c_ndarray = np.zeros(a_size_m * b_size_n).reshape(a_size_m, b_size_n)
    
    #行列積計算
    for i in range(a_size_m):
        for j in range(b_size_n):
            for k in range(a_size_n):
                c_ndarray[i, j] += a_ndarray[i, k] * b_ndarray[k, j]
    
    return c_ndarray

a_ndarray = np.array([[-1, 2, 3], 
                                        [4, -5, 6],
                                        [7, 8, -9]])

#エラーメッセージを出力させるため、行列Bのサイズを４×3とした。
b_ndarray = np.array([[0, 2, 1], 
                                       [0, 2, -8],
                                       [1, 2, 3],
                                        [2, 9, -1]])


c_ndarray = compute_matrix_product(a_ndarray, b_ndarray)
print(c_ndarray)

行列のサイズに問題があるため、計算結果が誤っている可能性があります。
[[  3.   8.  -8.]
 [  6.  10.  62.]
 [ -9.  12. -84.]]


In [33]:
#【問題6】転置
#問題５の行列Bを転置させ、行列積を求める。
import numpy as np

def compute_matrix_product(a_ndarray, b_ndarray):
    
    #行列Aのサイズ(m×n)を取得
    a_size_m = a_ndarray.shape[0]
    a_size_n = a_ndarray.shape[1]
    
    #行列Bのサイズ(m×n)を取得
    b_size_m = b_ndarray.shape[0]
    b_size_n = b_ndarray.shape[1]
    
    #行列積の計算可否を確認
    if a_size_n != b_size_m:
        print("行列のサイズに問題があるため、計算結果が誤っている可能性があります。")
    
    #行列Cのサイズの決定。各要素の初期値は０とする。
    c_ndarray = np.zeros(a_size_m * b_size_n).reshape(a_size_m, b_size_n)
    
    #行列積計算
    for i in range(a_size_m):
        for j in range(b_size_n):
            for k in range(a_size_n):
                c_ndarray[i, j] += a_ndarray[i, k] * b_ndarray[k, j]
    
    return c_ndarray

a_ndarray = np.array([[-1, 2, 3], 
                                        [4, -5, 6],
                                        [7, 8, -9]])

#行列Bのサイズを４×3としている。
b_ndarray = np.array([[0, 2, 1], 
                                       [0, 2, -8],
                                       [1, 2, 3],
                                        [2, 9, -1]])

#転置した行列Bにて行列積を求める。
c_ndarray = compute_matrix_product(a_ndarray, b_ndarray.T)
print(c_ndarray)


[[  7. -20.  12.  13.]
 [ -4. -58.  12. -43.]
 [  7.  88.  -4.  95.]]
