### 【問題1】練習のために特徴量の選択
データセットを読み込んだ後、説明変数GrLivAreaとYearBuilt、目的変数SalePriceをそれぞれ抜き出してください。

In [19]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris
data = load_iris()
X = data.data[:10]

scaler = StandardScaler()
scaler.fit(X)
print("平均 :", scaler.mean_)
print("分散 :", scaler.var_)
X_std = scaler.transform(X)



平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]


### 【問題1】これまで利用してきたクラスの列挙
クラスを使う際はインスタンス化を行うことと、クラスの命名法がわかりました。

この情報を元に、これまでの課題で利用してきたコードの中でどのようなクラスがあったかを答えてください。

Pandas、matplotlib、scikit-learnからそれぞれ1つ以上見つけてください。

→　Pandas : DataFrame()

　 matplot.lib : ListedColormap()

　 Scikit-learn : KNeighborsClassifier()

### 【問題2】これまで利用してきたメソッドやインスタンス変数の列挙

これまでの課題で利用してきたコードの中でどのようなメソッドやインスタンス変数があったかを答えてください。

最低でもそれぞれ5つ以上答えてください。

【インスタンス変数】

numpy: ndarray.T

numpy: ndarray.shape

numpy: ndarray.dtype

numpy: ndarray.ndim

Pandas : 列名の抽出var = df.columns.values

【メソッド】

numpy: array.tolist()

numpy: array.flatten()

numpy: array.reshape()

numpy: np.array()

numpy: np.arange()

numpy: np.concatenate((a, b), axis=1)

list.clear()

list.pop()

list.remove()

### 【問題3】標準化クラスをスクラッチで作成

理解をより深めるため、StandardScalerをスクラッチで作成しましょう。

scikit-learnは使わず、NumPyなどを活用して標準化の計算を記述します。

具体的にはfitメソッドとtransformメソッドを作ります。

In [28]:
import numpy as np
from sklearn.datasets import load_iris

class ScratchStandardScaler():
    def fit(self, X):
        self.mean_ = np.mean(X, axis=0)
        self.var_ = np.var(X, axis=0) 
        
    def transform(self, X):
        X_scaled = (X - self.mean_) / self.var_
        return X_scaled
    
data = load_iris()
X = data.data[:10]

scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("平均 : {}".format(scratch_scaler.mean_))
print("分散 : {}".format(scratch_scaler.var_))
X_std = scratch_scaler.transform(X)
print(X_std)


平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]
[[  3.14136126   2.23792697  -4.76190476  -3.57142857]
 [  0.52356021  -3.65135453  -4.76190476  -3.57142857]
 [ -2.09424084  -1.29564193 -14.28571429  -3.57142857]
 [ -3.40314136  -2.47349823   4.76190476  -3.57142857]
 [  1.83246073   3.41578327  -4.76190476  -3.57142857]
 [  7.06806283   6.94935218  23.80952381  32.14285714]
 [ -3.40314136   1.06007067  -4.76190476  14.28571429]
 [  1.83246073   1.06007067   4.76190476  -3.57142857]
 [ -6.02094241  -4.82921084  -4.76190476  -3.57142857]
 [  0.52356021  -2.47349823   4.76190476 -21.42857143]]


### 【問題4】 四則演算を行うクラスの作成

上記ExampleClassは足し算のメソッドを持っていますが、これに引き算、掛け算、割り算のメソッドを加えてください。

コンストラクタに入力されたvalueが文字列や配列など数値以外だった場合にはエラーを出すようにしてください。

クラス名や説明文も適切に書き換えてください。

In [55]:
class ExampleClass():
    """
    説明用の簡単なクラス
    Parameters
    ----------
    value : float or int
        初期値
    Attributes
    ----------
    value : float or int
        計算結果
    """
    def __init__(self, value):
        print(type(value))
        if type(value) is int:
            self.value = value
            print("初期値{}が設定されました".format(self.value))
            
        elif type(value) is float:
            self.value = value
            print("初期値{}が設定されました".format(self.value))
            
        else:
            raise ValueError("Inputted Number type is inappropriate. Please input 'int' or 'float'")
        
    def add(self, value2):
        """
        受け取った引数をself.valueに加える
        """
        self.value += value2
        
    def subtract(self, value3):
        """
        受け取った引数をself.valueから引く
        """
        self.value -= value3

    def multiply(self, value4):
        """
        受け取った引数をself.valueに掛ける
        """
        self.value *= value4
        
    def divide(self, value5):
        """
        受け取った引数をself.valueに対して割る
        """
        self.value /= value5
        
example = ExampleClass(11.1)
print("value : {}".format(example.value))
example.add(3)
print("value : {}".format(example.value))
example.subtract(2)
print("value : {}".format(example.value))
example.multiply(3)
print("value : {}".format(example.value))
example.divide(9)
print("value : {}".format(example.value))

<class 'float'>
初期値11.1が設定されました
value : 11.1
value : 14.1
value : 12.1
value : 36.3
value : 4.033333333333333
